language: java

# since not all JDKs are available in all environments
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: trusty
      jdk: openjdk9
    - os: linux
      dist: trusty
      jdk: openjdk9
git:
  depth: 10

before_script:
  - echo $HOME
  - java -version
  - echo $JAVA_OPTS
  - mvn -version
  - echo $MAVEN_OPTS

cache:
  directories:
    - $HOME/.m2/

script:
  - mvn clean test