language: java
virt: lxd #Not a full VM - faster startup w/ some limitations

# since not all JDKs are available in all environments
matrix:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk8
    - os: linux
      dist: focal
      jdk: openjdk9
    - os: linux
      dist: focal
      jdk: openjdk11
    - os: linux
      dist: focal
      jdk: openjdk16
git:
  depth: 10

before_script:
  - echo $HOME
  - java -version
  - echo $JAVA_OPTS
  - mvn -version
  - echo $MAVEN_OPTS

cache:
  directories:
    - $HOME/.m2/

script:
  - mvn clean test